[package]
name = "imgdup"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = {version = "0.29", features = ["blob"]}
thiserror = "1"
serde = {version = "1", features = ["derive"]}
bincode = "1"
once_cell = "1"
indexmap = "1"

[dev-dependencies]
tempfile = "3"
rand = {version = "0.8", features = ["small_rng"]}
