[package]
name = "imgdup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = {version = "0.29", features = ["blob"]}
thiserror = "1"
serde = {version = "1", features = ["derive"]}
bincode = "1"
once_cell = "1"
