# This test just runs border removal on all pics and outputs the results and intermediate
# steps for debugging.

import '../../lib.just'

default:
    @just --list --justfile '{{justfile()}}'

reset:
    rm -vrf output masks

mkdirs:
    mkdir -p output masks

run: reset mkdirs
    #!/bin/bash
    set -eu

    for pic in pics/*.jpg; do
        fname=$(basename "$pic" .jpg)
        echo "file: $fname"
        {{cargo-run}} border_remover -- -o "masks/$fname.png" --maskify "$@" "$pic" >/dev/null
        {{cargo-run}} border_remover -- -o "output/$fname.jpg" "$@" "$pic"
    done
