default:
    @just --list --justfile '{{justfile()}}'

version := "6.0.1"
source := "source"
install := "install"

# Flags copied from https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/blob/2-6.0-13/PKGBUILD?ref_type=tags
# Removed:
# --enable-avisynth \ Some scripting post-processing stuff?
# --enable-nvdec \ nvidia
# --enable-nvenc \ nvidia
arch_flags := """
  --disable-debug \
  --disable-static \
  --disable-stripping \
  --enable-amf \
  --enable-cuda-llvm \
  --enable-lto \
  --enable-fontconfig \
  --enable-gmp \
  --enable-gnutls \
  --enable-gpl \
  --enable-ladspa \
  --enable-libaom \
  --enable-libass \
  --enable-libbluray \
  --enable-libbs2b \
  --enable-libdav1d \
  --enable-libdrm \
  --enable-libfreetype \
  --enable-libfribidi \
  --enable-libgsm \
  --enable-libiec61883 \
  --enable-libjack \
  --enable-libjxl \
  --enable-libmodplug \
  --enable-libmp3lame \
  --enable-libopencore_amrnb \
  --enable-libopencore_amrwb \
  --enable-libopenjpeg \
  --enable-libopenmpt \
  --enable-libopus \
  --enable-libpulse \
  --enable-librav1e \
  --enable-librsvg \
  --enable-libsoxr \
  --enable-libspeex \
  --enable-libsrt \
  --enable-libssh \
  --enable-libsvtav1 \
  --enable-libtheora \
  --enable-libv4l2 \
  --enable-libvidstab \
  --enable-libvmaf \
  --enable-libvorbis \
  --enable-libvpl \
  --enable-libvpx \
  --enable-libwebp \
  --enable-libx264 \
  --enable-libx265 \
  --enable-libxcb \
  --enable-libxml2 \
  --enable-libxvid \
  --enable-libzimg \
  --enable-opencl \
  --enable-opengl \
  --enable-shared \
  --enable-version3 \
  --enable-vulkan
"""

all: clean clone configure build

clone:
    git clone --depth 1 --branch n{{version}} https://git.ffmpeg.org/ffmpeg.git {{source}}

configure:
    cd {{source}} && ./configure \
      --prefix={{justfile_directory() / install}} \
      --disable-programs \
      --disable-doc \
      {{arch_flags}}

build:
    cd {{source}} && make -j {{num_cpus()}} install

clean:
    rm -vrf {{install}} {{source}}
